# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [4]:
import numpy as np

a = np.arange(6)
print(a)

print('a.sum() =',a.sum())
print('np.sum(a) =',np.sum(a))
print('sum(a) =',sum(a))
print()
print('a.sum及np.sum()為陣列之函式；sum()則為python之函式，所有型態皆可以使用且答案相同。\n但運算的速度上，sum()比較慢')

[0 1 2 3 4 5]
a.sum() = 15
np.sum(a) = 15
sum(a) = 15

a.sum及np.sum()為陣列之函式；sum()則為python之函式，所有型態皆可以使用且答案相同。
但運算的速度上，sum()比較慢


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。

In [11]:
### 最小值最大值正規化(Min-Max Normalization)：將資料等比例縮放到 [0, 1] 區間。
### 公式為： Xnom = (X-Xmin)/(Xmax-Xmin)
### 或利用平均值Xmean，將資料縮放至[-1,1]之間 → 平均值正規化(Mean Normalization)
### 公式為: Xnom = (X-Xmean)/(Xmax-Xmin)

In [8]:
import numpy as np

In [13]:
A0 = np.random.random((5, 5))
A = A0.copy()

Amax = A.max()
Amin = A.min()
Amean = A.mean()

norA1 = (A-Amin)/(Amax-Amin)
norA2 = (A-Amean)/(Amax-Amin)
print('Min-Max Normalization')
print(norA1)
print('Mean Normalization')
print(norA2)



Min-Max Normalization
[[0.32618914 0.22671497 0.17733206 0.67199734 0.15991373]
 [0.79570178 0.05444892 0.70424418 0.51404198 0.82343747]
 [0.60818491 1.         0.46498686 0.4689045  0.        ]
 [0.29772578 0.51864332 0.79379561 0.13694882 0.56794614]
 [0.3342491  0.91651898 0.7833902  0.9473825  0.75934899]]
Mean Normalization
[[-0.19589275 -0.29536692 -0.34474983  0.14991545 -0.36216816]
 [ 0.27361989 -0.46763297  0.18216228 -0.00803991  0.30135558]
 [ 0.08610302  0.47791811 -0.05709504 -0.05317739 -0.52208189]
 [-0.22435611 -0.00343857  0.27171372 -0.38513307  0.04586425]
 [-0.18783279  0.39443709  0.26130831  0.42530061  0.2372671 ]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [ ]:
import numpy as np

A0 = np.arange(10)
A = A0.copy()



[ 0.29347583  0.59303277 -1.          0.38043546  0.63265939  0.32472618
  0.11340241  0.68136955  0.89905432  0.74769935]


In [26]:
import numpy as np

A0 = np.random.randint(1,100,10)
A = A0.copy()

print(A0)
Amax = A.max()
A[A==Amax]=-1
print(A)

[42 68 67 69 74 12 66 18 39 73]
[42 68 67 69 -1 12 66 18 39 73]
