# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [ ]:
import numpy as np
import time

In [24]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
print(Z)

[[[8 3 4 ... 2 8 4]
  [0 0 1 ... 1 6 1]
  [3 9 3 ... 3 1 9]
  ...
  [4 1 5 ... 1 6 2]
  [9 1 9 ... 7 1 1]
  [2 8 4 ... 2 3 3]]

 [[2 7 9 ... 5 9 7]
  [4 9 5 ... 0 6 9]
  [8 3 4 ... 4 3 4]
  ...
  [0 8 0 ... 7 4 8]
  [4 7 9 ... 9 0 8]
  [9 2 6 ... 9 1 4]]

 [[9 6 6 ... 3 5 2]
  [8 4 0 ... 2 3 4]
  [7 1 5 ... 5 9 8]
  ...
  [0 4 0 ... 6 2 5]
  [1 5 8 ... 6 6 1]
  [0 7 9 ... 4 1 4]]

 ...

 [[6 3 5 ... 9 5 3]
  [9 4 4 ... 1 2 9]
  [7 9 8 ... 2 6 2]
  ...
  [4 4 7 ... 9 6 3]
  [9 2 2 ... 4 1 3]
  [7 5 2 ... 8 0 5]]

 [[6 6 3 ... 9 2 3]
  [0 6 6 ... 6 7 9]
  [8 5 6 ... 2 3 9]
  ...
  [7 5 3 ... 4 1 0]
  [0 9 7 ... 6 6 0]
  [6 5 5 ... 9 0 6]]

 [[1 4 9 ... 8 4 2]
  [6 7 1 ... 8 5 8]
  [8 4 6 ... 6 3 5]
  ...
  [3 0 9 ... 7 5 1]
  [4 8 7 ... 1 7 5]
  [6 0 6 ... 2 9 9]]]


In [26]:
%timeit -n 10 a = 2

Z = Z+1

31.4 ns ± 7.81 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [27]:
%timeit -n 10 a = 2

Z_method2 = []

for i in Z.flat:
    Z_method2.append(i+1)
Z_method2=np.array(Z_method2).reshape(100,100,100)

31.5 ns ± 9.41 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [28]:
%timeit -n 10 a = 2

Z_method3 = []

for i in np.nditer(Z, order = 'C'):
    Z_method3.append(i+1)

Z_method3_array = np.array(Z_method3, dtype = int).reshape(100,100,100)

31.8 ns ± 8.48 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [16]:
import numpy as np

Z = np.random.randint(0,10,50)
Zc = Z.copy()
Zlst = Z.tolist() 
print(Z)
print(Zlst)


[6 6 1 1 2 0 5 1 1 4 9 2 8 2 8 5 9 8 0 0 5 0 8 2 4 6 5 0 4 0 0 4 2 9 9 4 6
 1 9 5 4 5 8 8 0 1 4 4 7 4]
[6, 6, 1, 1, 2, 0, 5, 1, 1, 4, 9, 2, 8, 2, 8, 5, 9, 8, 0, 0, 5, 0, 8, 2, 4, 6, 5, 0, 4, 0, 0, 4, 2, 9, 9, 4, 6, 1, 9, 5, 4, 5, 8, 8, 0, 1, 4, 4, 7, 4]


In [17]:
a = np.unique(Z)
A = a.tolist()
print(a)
print(A)

[0 1 2 4 5 6 7 8 9]
[0, 1, 2, 4, 5, 6, 7, 8, 9]


In [23]:
most=0
ct = 0
for i in A:
    if Zlst.count(i) > ct:
        ct = Zlst.count(i)
        most=i
position = np.where(Z == most)
print('最多的數值是',most,'共有',ct,'個')
print(position)

最多的數值是 4 共有 9 個
(array([ 9, 24, 28, 31, 35, 40, 46, 47, 49]),)


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [1]:
import numpy as np

a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[6, 1, 2, 8, 8, 8]
[6, 1, 2, 8, 8, 8]
[[5, 0, 9, 5], [3, 9, 2, 3], [8, 3, 1, 0]]
[array([5, 0, 9, 5]), array([3, 9, 2, 3]), array([8, 3, 1, 0])]
[[[9, 4], [8, 2], [6, 1]], [[4, 4], [3, 9], [9, 6]]]
[array([[9, 4],
       [8, 2],
       [6, 1]]), array([[4, 4],
       [3, 9],
       [9, 6]])]


In [2]:
def newtolist(array):
    newlist = []
    if array.ndim == 3:
        for x in range(0,array.shape[0]):
            for y in range(0,array.shape[1]):
                newlist.append(list(c[x][y]))
        return newlist
    if array.ndim == 2:
        for x in range(0,array.shape[0]):
            newlist.append(list(array[x]))
        return newlist
    else:
        return list(array)

a = np.random.randint(10, size=6)
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2))

print(newtolist(a))
print(newtolist(b))
print(newtolist(c))

[2, 3, 1, 6, 6, 0]
[[5, 6, 3, 8], [6, 2, 0, 9], [1, 3, 2, 2]]
[[3, 8], [2, 9], [2, 7], [6, 0], [9, 1], [2, 1]]
