# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [3]:
import numpy as np

print(np.zeros((2, 3)),'\n由0組成的陣列')
print(np.empty((2, 3)),'\n由極小亂數(近似0)組成的陣列，因為此陣列不會賦與特定的元素值，所以生成比較快')
print('以上兩者均可用來生成初始化固定大小陣列')

[[0. 0. 0.]
 [0. 0. 0.]] 
由0組成的陣列
[[0. 0. 0.]
 [0. 0. 0.]] 
由極小亂數(近似0)組成的陣列，因為此陣列不會賦與特定的元素值，所以生成比較快
以上兩者均可用來生成初始化固定大小陣列


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [9]:
import numpy as np

In [23]:
a = np.random.rand(2, 3)
b = a.copy()

print(a)
print(np.array(b,dtype=int))

[[0.65080184 0.19715666 0.90525767]
 [0.24209851 0.07492912 0.19749986]]
[[0 0 0]
 [0 0 0]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [38]:
m = 20
n = 40

import numpy as np
from numpy.random import default_rng
rng = default_rng()
integers = rng.integers(m,n, size=(2,3))

print(integers)

[[26 30 39]
 [37 37 25]]


In [41]:
import numpy as np

a = np.random.rand(2,3)
b = a.copy()
c = b*(n-m)+m
print(np.array(c,dtype=int))

[[20 27 24]
 [31 38 32]]


In [43]:
import numpy as np
m = 20
n = 40
a = np.random.randint(m,n, size=(2,3))
print(np.array(a,dtype=int))

[[36 35 24]
 [37 28 22]]
