# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```


In [11]:
import numpy as np

a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] )

print(a + a)
print(a + b)
print(a + c)
print(a + d)
print('print(a + e) 不符合Boardcast原則，無法運算')
print(a + e)

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]
print(a + e) 不符合Boardcast原則，無法運算


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


In [5]:
# 記得先 Import 正確的套件

import numpy as np


In [16]:
A = np.ones(3)*1
B = np.ones(3)*2

print('A =',A)
print('B =',B)

print('不用迴圈的情況下\n直接用(A+B)*(-A/2)運算\n可得結果為',(A+B)*(-A/2))

#使用迴圈
byloop=[]

for i in np.arange(A.size):
    x= (A[i]+B[i])*(-A[i]/2)
    byloop.append(x)

print('利用迴圈亦可得到結果',byloop)




A = [1. 1. 1.]
B = [2. 2. 2.]
不用迴圈的情況下
直接用(A+B)*(-A/2)運算
可得結果為 [-1.5 -1.5 -1.5]
利用迴圈亦可得到結果 [-1.5, -1.5, -1.5]


### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


In [19]:
A = np.ones((1,6))
B = np.ones((6,1))

#內積
print(np.dot(A,B))
print(A@B)
#外積
print(np.outer(A,B)) 
print(A*B)

[[6.]]
[[6.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
