# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [3]:
import numpy as np

a = np.arange(1,12)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [6]:
a = np.arange(1,12)

final = []
for i in a:
    if 3 <= i <=6:
        x = i* (-1)
        final.append(x)
    else: 
        final.append(i)
print(final)

[1, 2, -3, -4, -5, -6, 7, 8, 9, 10, 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [7]:
A = np.random.rand(3, 6)

print (A)

[[0.90435319 0.40636885 0.95198276 0.85091105 0.87572983 0.78346049]
 [0.32913497 0.83839847 0.25935586 0.29107786 0.12573757 0.53271803]
 [0.99475647 0.2439199  0.62016102 0.09644875 0.36143376 0.07523215]]


In [13]:
newA = A<0.5
print(newA)
print(A[newA])
print("大於0.5的數有", len(A[newA]),"個")

[[False  True False False False False]
 [ True False  True  True  True False]
 [False  True False  True  True  True]]
[0.40636885 0.32913497 0.25935586 0.29107786 0.12573757 0.2439199
 0.09644875 0.36143376 0.07523215]
大於0.5的數有 9 個
